# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0003_gj_drvna_zaliha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gj',
            name='etat_povrsina',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='gj',
            name='etat_zaliha',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='gj',
            name='prirast',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='gj',
            name='drvna_zaliha',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
